{
	"jobConfig": {
		"name": "healthcare-etl-job",
		"description": "",
		"role": "arn:aws:iam::669167971432:role/GlueHealthcareRole",
		"command": "glueetl",
		"version": "3.0",
		"runtime": null,
		"workerType": "G.1X",
		"numberOfWorkers": 2,
		"maxCapacity": 2,
		"jobRunQueuingEnabled": false,
		"maxRetries": 0,
		"timeout": 10,
		"maxConcurrentRuns": 1,
		"security": "none",
		"scriptName": "healthcare-etl-job.py",
		"scriptLocation": "s3://aws-glue-assets-669167971432-us-east-2/scripts/",
		"language": "python-3",
		"spark": true,
		"sparkConfiguration": "standard",
		"jobParameters": [],
		"tags": [],
		"jobMode": "DEVELOPER_MODE",
		"createdOn": "2026-06-03T02:33:10.174Z",
		"developerMode": true,
		"connectionsList": [],
		"temporaryDirectory": "s3://aws-glue-assets-669167971432-us-east-2/temporary/",
		"logging": true,
		"glueHiveMetastore": true,
		"etlAutoTuning": true,
		"metrics": true,
		"observabilityMetrics": true,
		"bookmark": "job-bookmark-disable",
		"sparkPath": "s3://aws-glue-assets-669167971432-us-east-2/sparkHistoryLogs/",
		"flexExecution": false,
		"minFlexWorkers": null,
		"maintenanceWindow": null
	},
	"hasBeenSaved": false,
	"usageProfileName": null,
	"script": "import sys\r\nfrom awsglue.transforms import *\r\nfrom awsglue.utils import getResolvedOptions\r\nfrom pyspark.context import SparkContext\r\nfrom awsglue.context import GlueContext\r\nfrom awsglue.job import Job\r\nfrom pyspark.sql import functions as F\r\nfrom pyspark.sql.functions import col, when, to_date, hour\r\n\r\nargs = getResolvedOptions(sys.argv, ['JOB_NAME'])\r\nsc = SparkContext()\r\nglueContext = GlueContext(sc)\r\nspark = glueContext.spark_session\r\njob = Job(glueContext)\r\njob.init(args['JOB_NAME'], args)\r\n\r\n# ---Step-1---\r\nBUCKET = 's3://patient-health-monitoring-arbin-669167971432-us-east-2-an'  \r\n\r\nvitals_df = spark.read.option('header', 'true').csv(BUCKET + '/raw/vitals/')\r\npatients_df = spark.read.option('header', 'true').csv(BUCKET + '/raw/patients/')\r\ndevices_df = spark.read.option('header', 'true').csv(BUCKET + '/raw/devices/')\r\n\r\n\r\nvitals_df = vitals_df.dropDuplicates()\r\n\r\nvitals_df = vitals_df.fillna({'heart_rate': '72', 'oxygen_level': '95'})\r\n\r\nvitals_df = vitals_df \\\r\n    .withColumn('heart_rate', col('heart_rate').cast('integer')) \\\r\n    .withColumn('oxygen_level', col('oxygen_level').cast('integer')) \\\r\n    .withColumn('temperature', col('temperature').cast('double'))\r\n\r\n#---Step-3---\r\nvitals_df = vitals_df.withColumn('health_status',\r\n    when(col('oxygen_level') < 90, 'Critical')\r\n    .when(col('temperature') > 100, 'Fever')\r\n    .when(col('heart_rate') > 100, 'High Risk')\r\n    .otherwise('Normal')\r\n)\r\n\r\nvitals_df = vitals_df.withColumn('alert_flag',\r\n    when(col('health_status') != 'Normal', True).otherwise(False)\r\n)\r\n\r\nvitals_df = vitals_df \\\r\n    .withColumn('monitoring_date', to_date(col('timestamp'))) \\\r\n    .withColumn('monitoring_hour', hour(col('timestamp').cast('timestamp')))\r\n\r\n3\r\n# --- Step-4 ---\r\njoined_df = vitals_df \\\r\n    .join(patients_df, on='patient_id', how='left') \\\r\n    .join(devices_df, on='patient_id', how='left')\r\n\r\n\r\nfinal_df = joined_df.select(\r\n    'patient_id',\r\n    col('name').alias('patient_name'),\r\n    'disease',\r\n    'heart_rate',\r\n    'oxygen_level',\r\n    'temperature',\r\n    'health_status',\r\n    'alert_flag',\r\n    'device_type',\r\n    'monitoring_date',\r\n    'monitoring_hour'\r\n)\r\n\r\n\r\nrejected_df = final_df.filter(col('patient_name').isNull())\r\ngood_df = final_df.filter(col('patient_name').isNotNull())\r\n\r\n\r\ngood_df.write.mode('overwrite').parquet(BUCKET + '/processed/reports/')\r\nrejected_df.write.mode('overwrite').parquet(BUCKET + '/rejected/')\r\n\r\nprint('ETL job completed successfully!')\r\njob.commit()\r\n\r\n"
}