import Link from "next/link";
import { ArrowRight, Trophy } from "lucide-react";
import { LegendPick } from "@/components/LegendPick";

export default function HomePage() {
  return (
    <main className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center gap-8 px-6 py-16">
      <div className="glass-panel rounded-3xl p-10">
        <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-neon/30 bg-neon/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-neon">
          <Trophy className="h-4 w-4" aria-hidden />
          World Cup Mode
        </div>
        <h1 className="text-4xl font-semibold leading-tight text-white md:text-5xl">
          History, data, and{" "}
          <span className="text-neon">2026 predictions</span> in one hub.
        </h1>
        <p className="mt-4 text-lg text-zinc-400">
          Explore 2014–2022 finals, then lock in your scorelines for the
          48-team tournament in North America.
        </p>
        <p className="mt-3 text-base text-zinc-300">
          (Will Messi play this 2026 World Cup?)
        </p>
        <div className="mt-8 flex flex-wrap items-center gap-4">
          <Link
            href="/dashboard"
            className="inline-flex items-center gap-2 rounded-full bg-neon px-6 py-3 text-sm font-semibold text-pitch shadow-neon transition hover:bg-neon-dim"
          >
            Open dashboard
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
          <Link
            href="/songs"
            className="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3 text-sm font-semibold text-zinc-200 transition hover:border-neon/40 hover:text-white"
          >
            World Cup songs &amp; voting
            <ArrowRight className="h-4 w-4" aria-hidden />
          </Link>
        </div>
      </div>

      <section className="glass-panel rounded-3xl p-8 md:p-10">
        <p className="text-xs font-semibold uppercase tracking-[0.25em] text-neon">
          Context: popularity, reach, and pay
        </p>
        <h2 className="mt-3 text-2xl font-semibold text-white md:text-3xl">
          Men&apos;s vs Women&apos;s World Cup
        </h2>

        <div className="mt-6 space-y-4 text-sm text-zinc-300 md:text-base">
          <p>
            The men&apos;s FIFA World Cup has existed since 1930, while the
            Women&apos;s World Cup began in 1991. That longer timeline gave the
            men&apos;s tournament more time to build global audiences, media
            rights value, and commercial ecosystems.
          </p>
          <p>
            Today, when people say the men&apos;s game is bigger, they usually
            mean current audience and revenue size: larger TV contracts, higher
            sponsorship totals, and stronger ticket demand in many markets.
          </p>
          <p>
            Athlete pay is typically linked to money generated by leagues and
            tournaments. Historically, men&apos;s competitions have produced more
            revenue, which is why salaries and prize pools have often been
            higher.
          </p>
          <p>
            That does not mean men&apos;s football is better. Women&apos;s football
            is elite, highly competitive, and growing quickly, with recent
            Women&apos;s World Cups setting major viewership milestones and closing
            the commercial gap over time.
          </p>
        </div>
      </section>
      <LegendPick />
      <p className="text-center text-xs text-zinc-500">
        Stack: Next.js · Tailwind · Supabase · Framer Motion
      </p>
    </main>
  );
}
